/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaceVerifyRouteImport } from './routes/face-verify'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceVerifyRoute = FaceVerifyRouteImport.update({
  id: '/face-verify',
  path: '/face-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/face-verify': typeof FaceVerifyRoute
  '/login': typeof LoginRoute
  '/students': typeof StudentsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/face-verify': typeof FaceVerifyRoute
  '/login': typeof LoginRoute
  '/students': typeof StudentsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/face-verify': typeof FaceVerifyRoute
  '/login': typeof LoginRoute
  '/students': typeof StudentsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/depenses'
    | '/face-verify'
    | '/login'
    | '/students'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/depenses' | '/face-verify' | '/login' | '/students' | '/verify'
  id:
    | '__root__'
    | '/'
    | '/depenses'
    | '/face-verify'
    | '/login'
    | '/students'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepensesRoute: typeof DepensesRoute
  FaceVerifyRoute: typeof FaceVerifyRoute
  LoginRoute: typeof LoginRoute
  StudentsRoute: typeof StudentsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-verify': {
      id: '/face-verify'
      path: '/face-verify'
      fullPath: '/face-verify'
      preLoaderRoute: typeof FaceVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepensesRoute: DepensesRoute,
  FaceVerifyRoute: FaceVerifyRoute,
  LoginRoute: LoginRoute,
  StudentsRoute: StudentsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
